// Generated by gencpp from file new_gigacha/Path.msg
// DO NOT EDIT!


#ifndef NEW_GIGACHA_MESSAGE_PATH_H
#define NEW_GIGACHA_MESSAGE_PATH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace new_gigacha
{
template <class ContainerAllocator>
struct Path_
{
  typedef Path_<ContainerAllocator> Type;

  Path_()
    : x()
    , y()
    , heading()
    , k()
    , env()
    , mission()  {
    }
  Path_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , heading(_alloc)
    , k(_alloc)
    , env(_alloc)
    , mission(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _x_type;
  _x_type x;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _y_type;
  _y_type y;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _heading_type;
  _heading_type heading;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _k_type;
  _k_type k;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _env_type;
  _env_type env;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _mission_type;
  _mission_type mission;





  typedef boost::shared_ptr< ::new_gigacha::Path_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::new_gigacha::Path_<ContainerAllocator> const> ConstPtr;

}; // struct Path_

typedef ::new_gigacha::Path_<std::allocator<void> > Path;

typedef boost::shared_ptr< ::new_gigacha::Path > PathPtr;
typedef boost::shared_ptr< ::new_gigacha::Path const> PathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::new_gigacha::Path_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::new_gigacha::Path_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::new_gigacha::Path_<ContainerAllocator1> & lhs, const ::new_gigacha::Path_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.heading == rhs.heading &&
    lhs.k == rhs.k &&
    lhs.env == rhs.env &&
    lhs.mission == rhs.mission;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::new_gigacha::Path_<ContainerAllocator1> & lhs, const ::new_gigacha::Path_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace new_gigacha

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::new_gigacha::Path_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::new_gigacha::Path_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::new_gigacha::Path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::new_gigacha::Path_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_gigacha::Path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_gigacha::Path_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::new_gigacha::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c0d921e9132160b23d521caaec99f12";
  }

  static const char* value(const ::new_gigacha::Path_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c0d921e9132160bULL;
  static const uint64_t static_value2 = 0x23d521caaec99f12ULL;
};

template<class ContainerAllocator>
struct DataType< ::new_gigacha::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "new_gigacha/Path";
  }

  static const char* value(const ::new_gigacha::Path_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::new_gigacha::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] x\n"
"float64[] y\n"
"float64[] heading\n"
"float64[] k\n"
"string[] env\n"
"string[] mission\n"
;
  }

  static const char* value(const ::new_gigacha::Path_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::new_gigacha::Path_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.heading);
      stream.next(m.k);
      stream.next(m.env);
      stream.next(m.mission);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Path_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::new_gigacha::Path_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::new_gigacha::Path_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "heading[]" << std::endl;
    for (size_t i = 0; i < v.heading.size(); ++i)
    {
      s << indent << "  heading[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.heading[i]);
    }
    s << indent << "k[]" << std::endl;
    for (size_t i = 0; i < v.k.size(); ++i)
    {
      s << indent << "  k[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.k[i]);
    }
    s << indent << "env[]" << std::endl;
    for (size_t i = 0; i < v.env.size(); ++i)
    {
      s << indent << "  env[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.env[i]);
    }
    s << indent << "mission[]" << std::endl;
    for (size_t i = 0; i < v.mission.size(); ++i)
    {
      s << indent << "  mission[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mission[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEW_GIGACHA_MESSAGE_PATH_H
